import pyautogui

pyautogui.press('win')
pyautogui.write('excel')
pyautogui.press('enter')
pyautogui.confirm(text='O Excel já abriu?', title='Passo 1', buttons=['Sim', 'Nao'])
pyautogui.press('win')
pyautogui.write('edge')
pyautogui.press('enter', interval=3)
pyautogui.confirm(text='O Edge já abriu?', title='Passo 2', buttons=['Sim', 'Nao'])
pyautogui.write('google.com')
pyautogui.press('enter')
pyautogui.confirm(text='O Google já carregou?', title='Passo 3', buttons=['Sim', 'Nao'])
pyautogui.write('dolar hoje real')
pyautogui.press('enter')
pyautogui.confirm(text='A pesquisa já abriu?', title='Passo 4', buttons=['Sim', 'Nao'])
pyautogui.moveTo(233, 323, duration=5)
pyautogui.doubleClick()
pyautogui.hotkey('ctrl','c')
pyautogui.hotkey('alt','tab')
pyautogui.win.maximize()
pyautogui.moveTo(710, 572, duration=3)
pyautogui.write('February2022')
pyautogui.press('enter')
pyautogui.press('left')
pyautogui.hotkey('ctrl','v')